Jenkinsfile

Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>

Create initial build script

---

Jenkinsfile
__tests__/__integration__/cli/__snapshots__/cli.mqsc.integration.test.ts.snap
__tests__/__src__/environment/TempTestProfiles.ts
__tests__/__src__/environment/TestEnvironment.ts
__tests__/__system__/api/api.mqsc.system.test.ts
__tests__/api/MQSCCommand.unit.test.ts
__tests__/cli/MQSessionUtils.unit.test.ts
__tests__/cli/command/Command.definition.unit.test.ts
__tests__/cli/command/mqsc/MQSCCommand.definition.unit.test.ts
package-lock.json
package.json
src/api/MQSCCommand.ts
src/api/rest/MQRestClient.ts
src/api/rest/MQSession.ts
src/api/rest/__tests__/MQRestClient.unit.test.ts
src/api/rest/constants/MQ.messages.ts
src/cli/MQBaseHandler.ts
src/cli/MQSessionUtils.ts
src/cli/command/Command.definition.ts
src/cli/command/mqsc/MQSCCommand.definition.ts
src/cli/command/mqsc/MQSCCommand.handler.ts
src/imperative.ts

Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>

Switch to @zowe from @brightside

---

CHANGELOG.md
__tests__/imperative.test.ts
package.json

Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>

Bump version number

---

Jenkinsfile

Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>

Set to manually control version number

---

.codecov.yml
README.md
__tests__/__src__/environment/TestEnvironment.ts
package.json

- Naming changed onf various md files
- Package name changed
- Coverage results set to be the same or higher than `base`
- Update `package.json#version`
Signed-off-by: zFernand0 <fernando.rijocedeno@broadcom.com>

Change name for conformant plugin

---

CONTRIBUTING.md
README.md

This PR contains the following updates to the README.md file:
- Renamed plug-in using the proper branding
- Reorganized topics
- Added install info (registry vs. from source) described reasons to build from source
- Spell check/capitalization
- overall content cleanup
Merge the content updates into the master branch version of the Readme file.

Update the MQ Plug-in README.md file

---

.npmrc
package.json

Signed-off-by: Timothy Johnson <timothy.johnson@broadcom.com>

Add .npmrc that points to Zowe artifactory

---

Jenkinsfile
package.json

Also update pipeline script, use ^ instead of >= in package.json, and update a couple packages.
Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Update to create zowe-v1-lts tag

---

CHANGELOG.md
CONTRIBUTING.md

Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Update the changelog

---

CHANGELOG.md
__tests__/cli/command/mqsc/MQSCCommand.handler.unit.test.ts
src/cli/MQBaseHandler.ts
src/cli/MQSessionUtils.ts
src/cli/command/mqsc/MQSCCommand.handler.ts

Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Fixed daemon mode prompting, remove API call causing error

---

CHANGELOG.md
Jenkinsfile
__tests__/__snapshots__/imperative.test.ts.snap
src/imperative.ts

Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Remove apimlConnLookup

---

.github/workflows/audit.yml
.github/workflows/changelog.yml
.github/workflows/codeql.yml
.github/workflows/linter.yml
Jenkinsfile
package.json

Make branch references correct for v1-lts MQ pipelines

Protected branches for MQ v1

---

__tests__/__integration__/cli/__snapshots__/cli.mqsc.integration.test.ts.snap
npm-shrinkwrap.json
package.json

Signed-off-by: Timothy Johnson <timothy.johnson@broadcom.com>

Update Imperative and integration test snapshots

---

CHANGELOG.md
package.json

Q: Is it worth adding a changelog update and publishing a patch release to fix this?

Fix repository URL in package.json

---

CHANGELOG.md
package.json

[v1] Fix repository URL in package.json

---

.github/workflows/audit.yml
.github/workflows/changelog.yml
.github/workflows/codeql.yml
.github/workflows/linter.yml
.github/workflows/zowe-cli-plugin.yml

Action | Description
-- | --									
#6 | [update all workflows to remove deprecation warnings](https://github.com/zowe/zowe-cli-web-help-generator/pull/35/files), [octorelease updates](https://github.com/zowe/zowe-cli/pull/1712)										
#7 | remove Node 14 from workflow matrix

updating workflows - lts

---

.github/workflows/linter.yml
.github/workflows/zowe-cli-plugin.yml

Updated workflows to use Node 18 and 20

Use Node 18 and 20

---

.github/workflows/audit.yml
.github/workflows/auto-comment.yml
.github/workflows/changelog.yml
.github/workflows/codeql.yml
.github/workflows/linter.yml
.github/workflows/stale.yml
.github/workflows/zowe-cli-plugin.yml

Updates workflows to their supported Node 20 versions

Update Workflows to Node 20

---

CHANGELOG.md
__tests__/__system__/cli/cli.mqsc.system.test.ts
__tests__/cli/command/Command.definition.unit.test.ts
npm-shrinkwrap.json
package.json

Removes unnecessary await in test
Removes code smell for possibly undefined value in test
Adds Node engine string for v3

Update engine, add changelog, small lint tweaks

---

.github/workflows/codeql.yml

Update next branch to update CodeQL workflow to v3

Update next with master

---

CONTRIBUTING.md

Fix incorrect link to the CLI GitHub Repo
Change link to Imperative Wiki

Update incorrect links

---

package.json

Follow up to #78 that fixes the `__tests__/__results__/system/jest-stare` folder not being created.

Fix jest-stare output missing for system tests

---

.github/workflows/zowe-cli-plugin.yml
npm-shrinkwrap.json

Update workflows and deps for technical currency

---

__tests__/__integration__/cli/__snapshots__/cli.mqsc.integration.test.ts.snap
npm-shrinkwrap.json

Updates the shrinkwrap to pull the latest changes for dev deps.

chore: update shrinkwrap for dev deps
